// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateApiKeyOutputBody,
  CreateApiKeyRequestBody,
  DeleteApiKeyOutputBody,
  ExpireApiKeyOutputBody,
  ExpireApiKeyRequestBody,
  ListApiKeysOutputBody,
} from "../types/api-keys";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateDateTime } from "../validation";

export type ListApiKeysError = ErrorModel;

/**
 * Lists the API keys available to the authenticated user. Review each key's identifier, prefix, expiration, creation time, and last-seen time to manage existing credentials.
 */
export async function listApiKeys(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<ListApiKeysOutputBody> {
  const _resp = await sdkRequest<ListApiKeysOutputBody>({
    method: "GET",
    path: `/api/v1/apikey`,
    operationId: "listApiKeys",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type CreateApiKeyError = ErrorModel;

export type CreateApiKeyParams = CreateApiKeyRequestBody;

/**
 * Creates a new API key. You can provide `expiration` as a date-time value or omit it if you do not want to specify an expiration. The response contains the generated key in `apiKey`.
 *
 * @param expiration - Optional `date-time`-formatted value serialized in the
 *   `expiration` wire field.
 */
export async function createApiKey(
  config: ClientConfig,
  { expiration }: CreateApiKeyParams = {},
  requestOptions?: RequestOptions,
): Promise<CreateApiKeyOutputBody> {
  if (expiration != null) {
    validateDateTime("expiration", expiration);
  }

  const _resp = await sdkRequest<CreateApiKeyOutputBody>({
    method: "POST",
    path: `/api/v1/apikey`,
    operationId: "createApiKey",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      expiration,
    },
    config,
  });
  return _resp.data;
}

export type ExpireApiKeyError = ErrorModel;

export type ExpireApiKeyParams = ExpireApiKeyRequestBody;

/**
 * Expires an API key. Identify the key using `id`, `prefix`, or both, according to the key details available to you. The response confirms the operation with an empty object.
 *
 * @param id - Optional `uint64`-formatted value serialized in the `id` wire
 *   field.
 * @param prefix - Optional `string` value serialized in the `prefix` wire field.
 */
export async function expireApiKey(
  config: ClientConfig,
  { id, prefix }: ExpireApiKeyParams = {},
  requestOptions?: RequestOptions,
): Promise<ExpireApiKeyOutputBody> {
  const _resp = await sdkRequest<ExpireApiKeyOutputBody>({
    method: "POST",
    path: `/api/v1/apikey/expire`,
    operationId: "expireApiKey",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      id,
      prefix,
    },
    config,
  });
  return _resp.data;
}

export type DeleteApiKeyError = ErrorModel;

export interface DeleteApiKeyParams {
  prefix: string;
  id?: string;
}

/**
 * Deletes an API key selected by its prefix. You can also supply `id` as a uint64-formatted string to further identify the key. The response confirms the operation with an empty object.
 */
export async function deleteApiKey(
  config: ClientConfig,
  { prefix, id }: DeleteApiKeyParams,
  requestOptions?: RequestOptions,
): Promise<DeleteApiKeyOutputBody> {
  const _resp = await sdkRequest<DeleteApiKeyOutputBody>({
    method: "DELETE",
    path: `/api/v1/apikey/${encodePathSegment(prefix)}`,
    operationId: "deleteApiKey",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      id: queryValue(id, "form", false),
    },
    config,
  });
  return _resp.data;
}

export class ApiKeysNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists the API keys available to the authenticated user. Review each key's identifier, prefix, expiration, creation time, and last-seen time to manage existing credentials.
   */
  list(requestOptions?: RequestOptions): ReturnType<typeof listApiKeys> {
    return listApiKeys(this._config, requestOptions);
  }
  /**
   * Creates a new API key. You can provide `expiration` as a date-time value or omit it if you do not want to specify an expiration. The response contains the generated key in `apiKey`.
   */
  create(
    params: CreateApiKeyParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createApiKey> {
    return createApiKey(this._config, params, requestOptions);
  }
  /**
   * Expires an API key. Identify the key using `id`, `prefix`, or both, according to the key details available to you. The response confirms the operation with an empty object.
   */
  expire(
    params: ExpireApiKeyParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof expireApiKey> {
    return expireApiKey(this._config, params, requestOptions);
  }
  /**
   * Deletes an API key selected by its prefix. You can also supply `id` as a uint64-formatted string to further identify the key. The response confirms the operation with an empty object.
   */
  delete_(
    params: DeleteApiKeyParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteApiKey> {
    return deleteApiKey(this._config, params, requestOptions);
  }
}
