// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  AuthApproveOutputBody,
  AuthApproveRequestBody,
  AuthRegisterOutputBody,
  AuthRegisterRequestBody,
  AuthRejectOutputBody,
  AuthRejectRequestBody,
} from "../types/auth";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type AuthApproveError = ErrorModel;

export type AuthApproveParams = AuthApproveRequestBody;

/**
 * Approves a pending authentication session. Supply the session's `authId` to identify the request you want to approve. The response confirms the operation with an empty object.
 *
 * @param authId - Optional `string` value serialized in the `authId` wire field.
 */
export async function authApprove(
  config: ClientConfig,
  { authId }: AuthApproveParams = {},
  requestOptions?: RequestOptions,
): Promise<AuthApproveOutputBody> {
  const _resp = await sdkRequest<AuthApproveOutputBody>({
    method: "POST",
    path: `/api/v1/auth/approve`,
    operationId: "authApprove",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      authId,
    },
    config,
  });
  return _resp.data;
}

export type AuthRegisterError = ErrorModel;

export type AuthRegisterParams = AuthRegisterRequestBody;

/**
 * Registers a node through the authentication flow. Use `authId` to associate the registration with an authentication session and `user` to specify the user for the node. The response contains the registered node.
 *
 * @param authId - Optional `string` value serialized in the `authId` wire field.
 * @param user - Optional `string` value serialized in the `user` wire field.
 */
export async function authRegister(
  config: ClientConfig,
  { authId, user }: AuthRegisterParams = {},
  requestOptions?: RequestOptions,
): Promise<AuthRegisterOutputBody> {
  const _resp = await sdkRequest<AuthRegisterOutputBody>({
    method: "POST",
    path: `/api/v1/auth/register`,
    operationId: "authRegister",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      authId,
      user,
    },
    config,
  });
  return _resp.data;
}

export type AuthRejectError = ErrorModel;

export type AuthRejectParams = AuthRejectRequestBody;

/**
 * Rejects a pending authentication session. Supply the session's `authId` to identify the request you want to reject. The response confirms the operation with an empty object.
 *
 * @param authId - Optional `string` value serialized in the `authId` wire field.
 */
export async function authReject(
  config: ClientConfig,
  { authId }: AuthRejectParams = {},
  requestOptions?: RequestOptions,
): Promise<AuthRejectOutputBody> {
  const _resp = await sdkRequest<AuthRejectOutputBody>({
    method: "POST",
    path: `/api/v1/auth/reject`,
    operationId: "authReject",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      authId,
    },
    config,
  });
  return _resp.data;
}

export class AuthNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Approves a pending authentication session. Supply the session's `authId` to identify the request you want to approve. The response confirms the operation with an empty object.
   */
  approve(
    params: AuthApproveParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof authApprove> {
    return authApprove(this._config, params, requestOptions);
  }
  /**
   * Registers a node through the authentication flow. Use `authId` to associate the registration with an authentication session and `user` to specify the user for the node. The response contains the registered node.
   */
  register(
    params: AuthRegisterParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof authRegister> {
    return authRegister(this._config, params, requestOptions);
  }
  /**
   * Rejects a pending authentication session. Supply the session's `authId` to identify the request you want to reject. The response confirms the operation with an empty object.
   */
  reject(
    params: AuthRejectParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof authReject> {
    return authReject(this._config, params, requestOptions);
  }
}
