// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { HealthResponseBody } from "../types/health";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type HealthError = ErrorModel;

/**
 * Reports the server's health, including database connectivity. Read `databaseConnectivity` to determine whether the database connection is available.
 *
 * Reports server health, including database connectivity.
 */
export async function health(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<HealthResponseBody> {
  const _resp = await sdkRequest<HealthResponseBody>({
    method: "GET",
    path: `/api/v1/health`,
    operationId: "health",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class HealthNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Reports the server's health, including database connectivity. Read `databaseConnectivity` to determine whether the database connection is available.
   *
   * Reports server health, including database connectivity.
   */
  health(requestOptions?: RequestOptions): ReturnType<typeof health> {
    return health(this._config, requestOptions);
  }
}
