// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  BackfillNodeIPsOutputBody,
  DebugCreateNodeRequestBody,
  DeleteNodeOutputBody,
  ExpireNodeRequestBody,
  ListNodesOutputBody,
  NodeOutputBody,
  SetApprovedRoutesRequestBody,
  SetTagsRequestBody,
} from "../types/nodes";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";
import { validateDateTime } from "../validation";

export type DebugCreateNodeError = ErrorModel;

export type DebugCreateNodeParams = DebugCreateNodeRequestBody;

/**
 * Creates a node for debugging purposes. Provide `name` and `user` to describe the node, and use `key` or `routes` when those values are needed for the test setup. The response contains the created node.
 *
 * @param key - Optional `string` value serialized in the `key` wire field.
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param routes - Optional array value serialized in the `routes` wire field.
 * @param user - Optional `string` value serialized in the `user` wire field.
 */
export async function debugCreateNode(
  config: ClientConfig,
  { key, name, routes, user }: DebugCreateNodeParams = {},
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  const _resp = await sdkRequest<NodeOutputBody>({
    method: "POST",
    path: `/api/v1/debug/node`,
    operationId: "debugCreateNode",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      key,
      name,
      routes,
      user,
    },
    config,
  });
  return _resp.data;
}

export type ListNodesError = ErrorModel;

export interface ListNodesParams {
  user?: string;
}

/**
 * Lists nodes managed by the service. Supply `user` to filter the results to nodes associated with that user; omit it to list nodes without a user filter.
 */
export async function listNodes(
  config: ClientConfig,
  { user }: ListNodesParams = {},
  requestOptions?: RequestOptions,
): Promise<ListNodesOutputBody> {
  const _resp = await sdkRequest<ListNodesOutputBody>({
    method: "GET",
    path: `/api/v1/node`,
    operationId: "listNodes",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      user: queryValue(user, "form", false),
    },
    config,
  });
  return _resp.data;
}

export type BackfillNodeIpsError = ErrorModel;

export interface BackfillNodeIpsParams {
  confirmed?: boolean;
}

/**
 * Backfills IP addresses for registered nodes. Use the `confirmed` query parameter to indicate whether to confirm the operation, and review the returned `changes` list to see what was updated.
 */
export async function backfillNodeIps(
  config: ClientConfig,
  { confirmed }: BackfillNodeIpsParams = {},
  requestOptions?: RequestOptions,
): Promise<BackfillNodeIPsOutputBody> {
  const _resp = await sdkRequest<BackfillNodeIPsOutputBody>({
    method: "POST",
    path: `/api/v1/node/backfillips`,
    operationId: "backfillNodeIps",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      confirmed: queryValue(confirmed, "form", false),
    },
    config,
  });
  return _resp.data;
}

export type RegisterNodeError = ErrorModel;

export interface RegisterNodeParams {
  user?: string;
  key?: string;
}

/**
 * Registers a node and returns its node record. Use `user` to associate the node with a user and `key` to provide a registration key when needed.
 */
export async function registerNode(
  config: ClientConfig,
  { user, key }: RegisterNodeParams = {},
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  const _resp = await sdkRequest<NodeOutputBody>({
    method: "POST",
    path: `/api/v1/node/register`,
    operationId: "registerNode",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      user: queryValue(user, "form", false),
      key: queryValue(key, "form", false),
    },
    config,
  });
  return _resp.data;
}

export type DeleteNodeError = ErrorModel;

export interface DeleteNodeParams {
  nodeId: string;
}

/**
 * Deletes a node identified by its ID. Supply `nodeId` as an unsigned 64-bit integer value to identify the node to remove.
 */
export async function deleteNode(
  config: ClientConfig,
  { nodeId }: DeleteNodeParams,
  requestOptions?: RequestOptions,
): Promise<DeleteNodeOutputBody> {
  const _resp = await sdkRequest<DeleteNodeOutputBody>({
    method: "DELETE",
    path: `/api/v1/node/${encodePathSegment(nodeId)}`,
    operationId: "deleteNode",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type GetNodeError = ErrorModel;

export interface GetNodeParams {
  nodeId: string;
}

/**
 * Retrieves a node by its identifier. Supply `nodeId` as an unsigned 64-bit integer value to identify the node.
 */
export async function getNode(
  config: ClientConfig,
  { nodeId }: GetNodeParams,
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  const _resp = await sdkRequest<NodeOutputBody>({
    method: "GET",
    path: `/api/v1/node/${encodePathSegment(nodeId)}`,
    operationId: "getNode",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SetApprovedRoutesError = ErrorModel;

export type SetApprovedRoutesParams = SetApprovedRoutesRequestBody & {
  nodeId: string;
};

/**
 * Updates the approved routes for a node. Send the route values in the `routes` array to set which routes are approved for that node.
 *
 * @param routes - Optional array value serialized in the `routes` wire field.
 */
export async function setApprovedRoutes(
  config: ClientConfig,
  { nodeId, routes }: SetApprovedRoutesParams,
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  const _resp = await sdkRequest<NodeOutputBody>({
    method: "POST",
    path: `/api/v1/node/${encodePathSegment(nodeId)}/approve_routes`,
    operationId: "setApprovedRoutes",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      routes,
    },
    config,
  });
  return _resp.data;
}

export type ExpireNodeError = ErrorModel;

export type ExpireNodeParams = ExpireNodeRequestBody & {
  nodeId: string;
};

/**
 * Updates the expiry settings for a node. Supply `expiry` as an ISO 8601 date-time or use `disableExpiry` to specify whether expiry is disabled.
 *
 * @param disableExpiry - Optional `boolean` value serialized in the
 *   `disableExpiry` wire field.
 * @param expiry - Optional `date-time`-formatted value serialized in the
 *   `expiry` wire field.
 */
export async function expireNode(
  config: ClientConfig,
  { nodeId, disableExpiry, expiry }: ExpireNodeParams,
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  if (expiry != null) {
    validateDateTime("expiry", expiry);
  }

  const _resp = await sdkRequest<NodeOutputBody>({
    method: "POST",
    path: `/api/v1/node/${encodePathSegment(nodeId)}/expire`,
    operationId: "expireNode",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      disableExpiry,
      expiry,
    },
    config,
  });
  return _resp.data;
}

export type RenameNodeError = ErrorModel;

export interface RenameNodeParams {
  nodeId: string;
  newName: string;
}

/**
 * Renames a node by setting its new name. Supply the node identifier and the new name in the path.
 */
export async function renameNode(
  config: ClientConfig,
  { nodeId, newName }: RenameNodeParams,
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  const _resp = await sdkRequest<NodeOutputBody>({
    method: "POST",
    path: `/api/v1/node/${encodePathSegment(nodeId)}/rename/${encodePathSegment(newName)}`,
    operationId: "renameNode",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SetTagsError = ErrorModel;

export type SetTagsParams = SetTagsRequestBody & {
  nodeId: string;
};

/**
 * Sets the tags for a node. Send the tags as an array of strings in the request body.
 *
 * @param tags - Optional array value serialized in the `tags` wire field.
 */
export async function setTags(
  config: ClientConfig,
  { nodeId, tags }: SetTagsParams,
  requestOptions?: RequestOptions,
): Promise<NodeOutputBody> {
  const _resp = await sdkRequest<NodeOutputBody>({
    method: "POST",
    path: `/api/v1/node/${encodePathSegment(nodeId)}/tags`,
    operationId: "setTags",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      tags,
    },
    config,
  });
  return _resp.data;
}

export class NodesNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Creates a node for debugging purposes. Provide `name` and `user` to describe the node, and use `key` or `routes` when those values are needed for the test setup. The response contains the created node.
   */
  debugCreate(
    params: DebugCreateNodeParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof debugCreateNode> {
    return debugCreateNode(this._config, params, requestOptions);
  }
  /**
   * Lists nodes managed by the service. Supply `user` to filter the results to nodes associated with that user; omit it to list nodes without a user filter.
   */
  list(
    params: ListNodesParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof listNodes> {
    return listNodes(this._config, params, requestOptions);
  }
  /**
   * Backfills IP addresses for registered nodes. Use the `confirmed` query parameter to indicate whether to confirm the operation, and review the returned `changes` list to see what was updated.
   */
  backfillIps(
    params: BackfillNodeIpsParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof backfillNodeIps> {
    return backfillNodeIps(this._config, params, requestOptions);
  }
  /**
   * Registers a node and returns its node record. Use `user` to associate the node with a user and `key` to provide a registration key when needed.
   */
  register(
    params: RegisterNodeParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof registerNode> {
    return registerNode(this._config, params, requestOptions);
  }
  /**
   * Deletes a node identified by its ID. Supply `nodeId` as an unsigned 64-bit integer value to identify the node to remove.
   */
  delete_(
    params: DeleteNodeParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteNode> {
    return deleteNode(this._config, params, requestOptions);
  }
  /**
   * Retrieves a node by its identifier. Supply `nodeId` as an unsigned 64-bit integer value to identify the node.
   */
  get(params: GetNodeParams, requestOptions?: RequestOptions): ReturnType<typeof getNode> {
    return getNode(this._config, params, requestOptions);
  }
  /**
   * Updates the approved routes for a node. Send the route values in the `routes` array to set which routes are approved for that node.
   */
  setApprovedRoutes(
    params: SetApprovedRoutesParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof setApprovedRoutes> {
    return setApprovedRoutes(this._config, params, requestOptions);
  }
  /**
   * Updates the expiry settings for a node. Supply `expiry` as an ISO 8601 date-time or use `disableExpiry` to specify whether expiry is disabled.
   */
  expire(params: ExpireNodeParams, requestOptions?: RequestOptions): ReturnType<typeof expireNode> {
    return expireNode(this._config, params, requestOptions);
  }
  /**
   * Renames a node by setting its new name. Supply the node identifier and the new name in the path.
   */
  rename(params: RenameNodeParams, requestOptions?: RequestOptions): ReturnType<typeof renameNode> {
    return renameNode(this._config, params, requestOptions);
  }
  /**
   * Sets the tags for a node. Send the tags as an array of strings in the request body.
   */
  setTags(params: SetTagsParams, requestOptions?: RequestOptions): ReturnType<typeof setTags> {
    return setTags(this._config, params, requestOptions);
  }
}
