// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { CheckPolicyOutputBody, PolicyRequestBody, PolicyResponseBody } from "../types/policy";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { sdkRequest } from "../client";

export type GetPolicyError = ErrorModel;

/**
 * Retrieves the current policy. The response includes the policy text and the time it was last updated.
 */
export async function getPolicy(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<PolicyResponseBody> {
  const _resp = await sdkRequest<PolicyResponseBody>({
    method: "GET",
    path: `/api/v1/policy`,
    operationId: "getPolicy",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type SetPolicyError = ErrorModel;

export type SetPolicyParams = PolicyRequestBody;

/**
 * Replaces the current policy with the policy value supplied in the request body. Include the policy text in `policy`; the response provides the saved policy and its update time.
 *
 * @param policy - Optional `string` value serialized in the `policy` wire field.
 */
export async function setPolicy(
  config: ClientConfig,
  { policy }: SetPolicyParams = {},
  requestOptions?: RequestOptions,
): Promise<PolicyResponseBody> {
  const _resp = await sdkRequest<PolicyResponseBody>({
    method: "PUT",
    path: `/api/v1/policy`,
    operationId: "setPolicy",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      policy,
    },
    config,
  });
  return _resp.data;
}

export type CheckPolicyError = ErrorModel;

export type CheckPolicyParams = PolicyRequestBody;

/**
 * Validates a policy against the server's live users and nodes without saving it. Provide `policy` as a string when included; the request body is required.
 *
 * Validates the given policy against the server's live users and nodes without persisting it.
 *
 * @param policy - Optional `string` value serialized in the `policy` wire field.
 */
export async function checkPolicy(
  config: ClientConfig,
  { policy }: CheckPolicyParams = {},
  requestOptions?: RequestOptions,
): Promise<CheckPolicyOutputBody> {
  const _resp = await sdkRequest<CheckPolicyOutputBody>({
    method: "POST",
    path: `/api/v1/policy/check`,
    operationId: "checkPolicy",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      policy,
    },
    config,
  });
  return _resp.data;
}

export class PolicyNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Retrieves the current policy. The response includes the policy text and the time it was last updated.
   */
  get(requestOptions?: RequestOptions): ReturnType<typeof getPolicy> {
    return getPolicy(this._config, requestOptions);
  }
  /**
   * Replaces the current policy with the policy value supplied in the request body. Include the policy text in `policy`; the response provides the saved policy and its update time.
   */
  set(params: SetPolicyParams = {}, requestOptions?: RequestOptions): ReturnType<typeof setPolicy> {
    return setPolicy(this._config, params, requestOptions);
  }
  /**
   * Validates a policy against the server's live users and nodes without saving it. Provide `policy` as a string when included; the request body is required.
   *
   * Validates the given policy against the server's live users and nodes without persisting it.
   */
  check(
    params: CheckPolicyParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof checkPolicy> {
    return checkPolicy(this._config, params, requestOptions);
  }
}
