// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreatePreAuthKeyRequestBody,
  DeletePreAuthKeyOutputBody,
  ExpirePreAuthKeyOutputBody,
  ExpirePreAuthKeyRequestBody,
  ListPreAuthKeysOutputBody,
  PreAuthKeyOutputBody,
} from "../types/pre-auth-keys";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { queryValue, sdkRequest } from "../client";
import { validateDateTime } from "../validation";

export type DeletePreAuthKeyError = ErrorModel;

export interface DeletePreAuthKeyParams {
  id?: string;
}

/**
 * Deletes a pre-auth key. Use the optional `id` query parameter to identify the key to delete; provide it as a uint64-formatted string when supplied.
 */
export async function deletePreAuthKey(
  config: ClientConfig,
  { id }: DeletePreAuthKeyParams = {},
  requestOptions?: RequestOptions,
): Promise<DeletePreAuthKeyOutputBody> {
  const _resp = await sdkRequest<DeletePreAuthKeyOutputBody>({
    method: "DELETE",
    path: `/api/v1/preauthkey`,
    operationId: "deletePreAuthKey",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      id: queryValue(id, "form", false),
    },
    config,
  });
  return _resp.data;
}

export type ListPreAuthKeysError = ErrorModel;

/**
 * Lists the pre-auth keys configured on the server. Use this operation to retrieve each key's user, key value, expiration, usage state, and ACL tags.
 */
export async function listPreAuthKeys(
  config: ClientConfig,
  requestOptions?: RequestOptions,
): Promise<ListPreAuthKeysOutputBody> {
  const _resp = await sdkRequest<ListPreAuthKeysOutputBody>({
    method: "GET",
    path: `/api/v1/preauthkey`,
    operationId: "listPreAuthKeys",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type CreatePreAuthKeyError = ErrorModel;

export type CreatePreAuthKeyParams = CreatePreAuthKeyRequestBody;

/**
 * Creates a pre-auth key for a user. Configure the key with fields such as `user`, `expiration`, `reusable`, `ephemeral`, and `aclTags`; `user` is a uint64-formatted string and `expiration` is a date-time.
 *
 * @param aclTags - Optional array value serialized in the `aclTags` wire field.
 * @param ephemeral - Optional `boolean` value serialized in the `ephemeral` wire
 *   field.
 * @param expiration - Optional `date-time`-formatted value serialized in the
 *   `expiration` wire field.
 * @param reusable - Optional `boolean` value serialized in the `reusable` wire
 *   field.
 * @param user - Optional `uint64`-formatted value serialized in the `user` wire
 *   field.
 */
export async function createPreAuthKey(
  config: ClientConfig,
  { aclTags, ephemeral, expiration, reusable, user }: CreatePreAuthKeyParams = {},
  requestOptions?: RequestOptions,
): Promise<PreAuthKeyOutputBody> {
  if (expiration != null) {
    validateDateTime("expiration", expiration);
  }

  const _resp = await sdkRequest<PreAuthKeyOutputBody>({
    method: "POST",
    path: `/api/v1/preauthkey`,
    operationId: "createPreAuthKey",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      aclTags,
      ephemeral,
      expiration,
      reusable,
      user,
    },
    config,
  });
  return _resp.data;
}

export type ExpirePreAuthKeyError = ErrorModel;

export type ExpirePreAuthKeyParams = ExpirePreAuthKeyRequestBody;

/**
 * Expires a pre-auth key. Supply its identifier in the `id` field as a uint64-formatted string when specifying which key to expire.
 *
 * @param id - Optional `uint64`-formatted value serialized in the `id` wire
 *   field.
 */
export async function expirePreAuthKey(
  config: ClientConfig,
  { id }: ExpirePreAuthKeyParams = {},
  requestOptions?: RequestOptions,
): Promise<ExpirePreAuthKeyOutputBody> {
  const _resp = await sdkRequest<ExpirePreAuthKeyOutputBody>({
    method: "POST",
    path: `/api/v1/preauthkey/expire`,
    operationId: "expirePreAuthKey",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      id,
    },
    config,
  });
  return _resp.data;
}

export class PreAuthKeysNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Deletes a pre-auth key. Use the optional `id` query parameter to identify the key to delete; provide it as a uint64-formatted string when supplied.
   */
  delete_(
    params: DeletePreAuthKeyParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deletePreAuthKey> {
    return deletePreAuthKey(this._config, params, requestOptions);
  }
  /**
   * Lists the pre-auth keys configured on the server. Use this operation to retrieve each key's user, key value, expiration, usage state, and ACL tags.
   */
  list(requestOptions?: RequestOptions): ReturnType<typeof listPreAuthKeys> {
    return listPreAuthKeys(this._config, requestOptions);
  }
  /**
   * Creates a pre-auth key for a user. Configure the key with fields such as `user`, `expiration`, `reusable`, `ephemeral`, and `aclTags`; `user` is a uint64-formatted string and `expiration` is a date-time.
   */
  create(
    params: CreatePreAuthKeyParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createPreAuthKey> {
    return createPreAuthKey(this._config, params, requestOptions);
  }
  /**
   * Expires a pre-auth key. Supply its identifier in the `id` field as a uint64-formatted string when specifying which key to expire.
   */
  expire(
    params: ExpirePreAuthKeyParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof expirePreAuthKey> {
    return expirePreAuthKey(this._config, params, requestOptions);
  }
}
