// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import {
  CreateUserRequestBody,
  DeleteUserOutputBody,
  ListUsersOutputBody,
  UserOutputBody,
} from "../types/users";
import { ErrorModel } from "../types/shared";
import type { ClientConfig, RequestOptions } from "../client";
import { encodePathSegment, queryValue, sdkRequest } from "../client";

export type ListUsersError = ErrorModel;

export interface ListUsersParams {
  id?: string;
  name?: string;
  email?: string;
}

/**
 * Lists users, with optional filters for user identifier, name, or email. Supply `id` as a uint64-formatted string when filtering by identifier; `name` and `email` are string filters.
 */
export async function listUsers(
  config: ClientConfig,
  { id, name, email }: ListUsersParams = {},
  requestOptions?: RequestOptions,
): Promise<ListUsersOutputBody> {
  const _resp = await sdkRequest<ListUsersOutputBody>({
    method: "GET",
    path: `/api/v1/user`,
    operationId: "listUsers",
    responseDecoder: "json",
    ...requestOptions,
    query: {
      id: queryValue(id, "form", false),
      name: queryValue(name, "form", false),
      email: queryValue(email, "form", false),
    },
    config,
  });
  return _resp.data;
}

export type CreateUserError = ErrorModel;

export type CreateUserParams = CreateUserRequestBody;

/**
 * Creates a user record. You can provide `name`, `displayName`, `email`, and `pictureUrl`; all defined fields are strings and none is marked as required.
 *
 * @param displayName - Optional `string` value serialized in the `displayName`
 *   wire field.
 * @param email - Optional `string` value serialized in the `email` wire field.
 * @param name - Optional `string` value serialized in the `name` wire field.
 * @param pictureUrl - Optional `string` value serialized in the `pictureUrl`
 *   wire field.
 */
export async function createUser(
  config: ClientConfig,
  { displayName, email, name, pictureUrl }: CreateUserParams = {},
  requestOptions?: RequestOptions,
): Promise<UserOutputBody> {
  const _resp = await sdkRequest<UserOutputBody>({
    method: "POST",
    path: `/api/v1/user`,
    operationId: "createUser",
    responseDecoder: "json",
    ...requestOptions,
    body: {
      displayName,
      email,
      name,
      pictureUrl,
    },
    config,
  });
  return _resp.data;
}

export type DeleteUserError = ErrorModel;

export interface DeleteUserParams {
  id: string;
}

/**
 * Deletes a user by identifier. Provide the user's `id` as a uint64-formatted string in the path.
 */
export async function deleteUser(
  config: ClientConfig,
  { id }: DeleteUserParams,
  requestOptions?: RequestOptions,
): Promise<DeleteUserOutputBody> {
  const _resp = await sdkRequest<DeleteUserOutputBody>({
    method: "DELETE",
    path: `/api/v1/user/${encodePathSegment(id)}`,
    operationId: "deleteUser",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export type RenameUserError = ErrorModel;

export interface RenameUserParams {
  oldId: string;
  newName: string;
}

/**
 * Renames a user by changing the name associated with the specified identifier. Provide `oldId` as a uint64-formatted string and `newName` as a string in the path.
 */
export async function renameUser(
  config: ClientConfig,
  { oldId, newName }: RenameUserParams,
  requestOptions?: RequestOptions,
): Promise<UserOutputBody> {
  const _resp = await sdkRequest<UserOutputBody>({
    method: "POST",
    path: `/api/v1/user/${encodePathSegment(oldId)}/rename/${encodePathSegment(newName)}`,
    operationId: "renameUser",
    responseDecoder: "json",
    ...requestOptions,
    config,
  });
  return _resp.data;
}

export class UsersNamespace {
  constructor(private readonly _config: ClientConfig) {}

  /**
   * Lists users, with optional filters for user identifier, name, or email. Supply `id` as a uint64-formatted string when filtering by identifier; `name` and `email` are string filters.
   */
  list(
    params: ListUsersParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof listUsers> {
    return listUsers(this._config, params, requestOptions);
  }
  /**
   * Creates a user record. You can provide `name`, `displayName`, `email`, and `pictureUrl`; all defined fields are strings and none is marked as required.
   */
  create(
    params: CreateUserParams = {},
    requestOptions?: RequestOptions,
  ): ReturnType<typeof createUser> {
    return createUser(this._config, params, requestOptions);
  }
  /**
   * Deletes a user by identifier. Provide the user's `id` as a uint64-formatted string in the path.
   */
  delete_(
    params: DeleteUserParams,
    requestOptions?: RequestOptions,
  ): ReturnType<typeof deleteUser> {
    return deleteUser(this._config, params, requestOptions);
  }
  /**
   * Renames a user by changing the name associated with the specified identifier. Provide `oldId` as a uint64-formatted string and `newName` as a string in the path.
   */
  rename(params: RenameUserParams, requestOptions?: RequestOptions): ReturnType<typeof renameUser> {
    return renameUser(this._config, params, requestOptions);
  }
}
