// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ApiKey` API schema.
 */
export interface ApiKey {
  /**
   * Required `date-time`-formatted value serialized in the `createdAt` wire field.
   */
  createdAt: string | null;
  /**
   * Required `date-time`-formatted value serialized in the `expiration` wire field.
   */
  expiration: string | null;
  /**
   * Required `uint64`-formatted value serialized in the `id` wire field.
   */
  id: string;
  /**
   * Required `date-time`-formatted value serialized in the `lastSeen` wire field.
   */
  lastSeen: string | null;
  /**
   * Required `string` value serialized in the `prefix` wire field.
   */
  prefix: string;
}

/**
 * Typed representation of the `CreateApiKeyOutputBody` API schema.
 */
export interface CreateApiKeyOutputBody {
  /**
   * Required `string` value serialized in the `apiKey` wire field.
   */
  apiKey: string;
}

/**
 * Typed representation of the `CreateApiKeyRequestBody` API schema.
 */
export interface CreateApiKeyRequestBody {
  /**
   * Optional `date-time`-formatted value serialized in the `expiration` wire field.
   */
  expiration?: string;
}

/**
 * Typed representation of the `DeleteApiKeyOutputBody` API schema.
 */
export type DeleteApiKeyOutputBody = Record<string, never>;

/**
 * Typed representation of the `ExpireApiKeyOutputBody` API schema.
 */
export type ExpireApiKeyOutputBody = Record<string, never>;

/**
 * Typed representation of the `ExpireApiKeyRequestBody` API schema.
 */
export interface ExpireApiKeyRequestBody {
  /**
   * Optional `uint64`-formatted value serialized in the `id` wire field.
   */
  id?: string;
  /**
   * Optional `string` value serialized in the `prefix` wire field.
   */
  prefix?: string;
}

/**
 * Typed representation of the `ListApiKeysOutputBody` API schema.
 */
export interface ListApiKeysOutputBody {
  /**
   * Required array value serialized in the `apiKeys` wire field.
   */
  apiKeys: ApiKey[];
}
