// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Node } from "./shared";

/**
 * Typed representation of the `AuthApproveOutputBody` API schema.
 */
export type AuthApproveOutputBody = Record<string, never>;

/**
 * Typed representation of the `AuthApproveRequestBody` API schema.
 */
export interface AuthApproveRequestBody {
  /**
   * Optional `string` value serialized in the `authId` wire field.
   */
  authId?: string;
}

/**
 * Typed representation of the `AuthRegisterOutputBody` API schema.
 */
export interface AuthRegisterOutputBody {
  /**
   * Required object value serialized in the `node` wire field.
   */
  node: Node;
}

/**
 * Typed representation of the `AuthRegisterRequestBody` API schema.
 */
export interface AuthRegisterRequestBody {
  /**
   * Optional `string` value serialized in the `authId` wire field.
   */
  authId?: string;
  /**
   * Optional `string` value serialized in the `user` wire field.
   */
  user?: string;
}

/**
 * Typed representation of the `AuthRejectOutputBody` API schema.
 */
export type AuthRejectOutputBody = Record<string, never>;

/**
 * Typed representation of the `AuthRejectRequestBody` API schema.
 */
export interface AuthRejectRequestBody {
  /**
   * Optional `string` value serialized in the `authId` wire field.
   */
  authId?: string;
}
