// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `HealthResponseBody` API schema.
 */
export interface HealthResponseBody {
  /**
   * Required `boolean` value serialized in the `databaseConnectivity` wire field.
   */
  databaseConnectivity: boolean;
}
