// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { Node } from "./shared";

/**
 * Typed representation of the `BackfillNodeIPsOutputBody` API schema.
 */
export interface BackfillNodeIPsOutputBody {
  /**
   * Required array value serialized in the `changes` wire field.
   */
  changes: string[];
}

/**
 * Typed representation of the `DebugCreateNodeRequestBody` API schema.
 */
export interface DebugCreateNodeRequestBody {
  /**
   * Optional `string` value serialized in the `key` wire field.
   */
  key?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional array value serialized in the `routes` wire field.
   */
  routes?: string[] | null;
  /**
   * Optional `string` value serialized in the `user` wire field.
   */
  user?: string;
}

/**
 * Typed representation of the `DeleteNodeOutputBody` API schema.
 */
export type DeleteNodeOutputBody = Record<string, never>;

/**
 * Typed representation of the `ExpireNodeRequestBody` API schema.
 */
export interface ExpireNodeRequestBody {
  /**
   * Optional `boolean` value serialized in the `disableExpiry` wire field.
   */
  disableExpiry?: boolean;
  /**
   * Optional `date-time`-formatted value serialized in the `expiry` wire field.
   */
  expiry?: string;
}

/**
 * Typed representation of the `ListNodesOutputBody` API schema.
 */
export interface ListNodesOutputBody {
  /**
   * Required array value serialized in the `nodes` wire field.
   */
  nodes: Node[];
}

/**
 * Typed representation of the `NodeOutputBody` API schema.
 */
export interface NodeOutputBody {
  /**
   * Required object value serialized in the `node` wire field.
   */
  node: Node;
}

/**
 * Typed representation of the `SetApprovedRoutesRequestBody` API schema.
 */
export interface SetApprovedRoutesRequestBody {
  /**
   * Optional array value serialized in the `routes` wire field.
   */
  routes?: string[] | null;
}

/**
 * Typed representation of the `SetTagsRequestBody` API schema.
 */
export interface SetTagsRequestBody {
  /**
   * Optional array value serialized in the `tags` wire field.
   */
  tags?: string[] | null;
}
