// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `CheckPolicyOutputBody` API schema.
 */
export type CheckPolicyOutputBody = Record<string, never>;

/**
 * Typed representation of the `PolicyRequestBody` API schema.
 */
export interface PolicyRequestBody {
  /**
   * Optional `string` value serialized in the `policy` wire field.
   */
  policy?: string;
}

/**
 * Typed representation of the `PolicyResponseBody` API schema.
 */
export interface PolicyResponseBody {
  /**
   * Required `string` value serialized in the `policy` wire field.
   */
  policy: string;
  /**
   * Required `date-time`-formatted value serialized in the `updatedAt` wire field.
   */
  updatedAt: string;
}
