// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { User } from "./shared";

/**
 * Typed representation of the `CreatePreAuthKeyRequestBody` API schema.
 */
export interface CreatePreAuthKeyRequestBody {
  /**
   * Optional array value serialized in the `aclTags` wire field.
   */
  aclTags?: string[] | null;
  /**
   * Optional `boolean` value serialized in the `ephemeral` wire field.
   */
  ephemeral?: boolean;
  /**
   * Optional `date-time`-formatted value serialized in the `expiration` wire field.
   */
  expiration?: string;
  /**
   * Optional `boolean` value serialized in the `reusable` wire field.
   */
  reusable?: boolean;
  /**
   * Optional `uint64`-formatted value serialized in the `user` wire field.
   */
  user?: string;
}

/**
 * Typed representation of the `DeletePreAuthKeyOutputBody` API schema.
 */
export type DeletePreAuthKeyOutputBody = Record<string, never>;

/**
 * Typed representation of the `ExpirePreAuthKeyOutputBody` API schema.
 */
export type ExpirePreAuthKeyOutputBody = Record<string, never>;

/**
 * Typed representation of the `ExpirePreAuthKeyRequestBody` API schema.
 */
export interface ExpirePreAuthKeyRequestBody {
  /**
   * Optional `uint64`-formatted value serialized in the `id` wire field.
   */
  id?: string;
}

/**
 * Typed representation of the `ListPreAuthKeysOutputBody` API schema.
 */
export interface ListPreAuthKeysOutputBody {
  /**
   * Required array value serialized in the `preAuthKeys` wire field.
   */
  preAuthKeys: PreAuthKey[];
}

/**
 * Typed representation of the `PreAuthKey` API schema.
 */
export interface PreAuthKey {
  /**
   * Required array value serialized in the `aclTags` wire field.
   */
  aclTags: string[];
  /**
   * Required `date-time`-formatted value serialized in the `createdAt` wire field.
   */
  createdAt: string;
  /**
   * Required `boolean` value serialized in the `ephemeral` wire field.
   */
  ephemeral: boolean;
  /**
   * Required `date-time`-formatted value serialized in the `expiration` wire field.
   */
  expiration: string;
  /**
   * Required `uint64`-formatted value serialized in the `id` wire field.
   */
  id: string;
  /**
   * Required `string` value serialized in the `key` wire field.
   */
  key: string;
  /**
   * Required `boolean` value serialized in the `reusable` wire field.
   */
  reusable: boolean;
  /**
   * Required `boolean` value serialized in the `used` wire field.
   */
  used: boolean;
  /**
   * Required object value serialized in the `user` wire field.
   */
  user: User;
}

/**
 * Typed representation of the `PreAuthKeyOutputBody` API schema.
 */
export interface PreAuthKeyOutputBody {
  /**
   * Required object value serialized in the `preAuthKey` wire field.
   */
  preAuthKey: PreAuthKey;
}
