// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

/**
 * Typed representation of the `ErrorDetail` API schema.
 */
export interface ErrorDetail {
  /**
   * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
   */
  location?: string;
  /**
   * Error message text
   */
  message?: string;
  /**
   * The value at the given location
   */
  value?: unknown;
}

/**
 * Typed representation of the `ErrorModel` API schema.
 */
export interface ErrorModel {
  /**
   * A human-readable explanation specific to this occurrence of the problem.

   * @example "Property foo is required but is missing."
   */
  detail?: string;
  /**
   * Optional list of individual error details
   */
  errors?: ErrorDetail[] | null;
  /**
   * A URI reference that identifies the specific occurrence of the problem.

   * @example "https://example.com/error-log/abc123"
   */
  instance?: string;
  /**
   * HTTP status code

   * @example 400
   */
  status?: number;
  /**
   * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.

   * @example "Bad Request"
   */
  title?: string;
  /**
   * A URI reference to human-readable documentation for the error.

   * @example "https://example.com/errors/example"
   */
  type?: string;
}

/**
 * Typed representation of the `Node` API schema.
 */
export interface Node {
  /**
   * Required array value serialized in the `approvedRoutes` wire field.
   */
  approvedRoutes: string[];
  /**
   * Required array value serialized in the `availableRoutes` wire field.
   */
  availableRoutes: string[];
  /**
   * Required `date-time`-formatted value serialized in the `createdAt` wire field.
   */
  createdAt: string;
  /**
   * Required `string` value serialized in the `discoKey` wire field.
   */
  discoKey: string;
  /**
   * Required `date-time`-formatted value serialized in the `expiry` wire field.
   */
  expiry: string | null;
  /**
   * Required `string` value serialized in the `givenName` wire field.
   */
  givenName: string;
  /**
   * Required `uint64`-formatted value serialized in the `id` wire field.
   */
  id: string;
  /**
   * Required array value serialized in the `ipAddresses` wire field.
   */
  ipAddresses: string[];
  /**
   * Required `date-time`-formatted value serialized in the `lastSeen` wire field.
   */
  lastSeen: string | null;
  /**
   * Required `string` value serialized in the `machineKey` wire field.
   */
  machineKey: string;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Required `string` value serialized in the `nodeKey` wire field.
   */
  nodeKey: string;
  /**
   * Required `boolean` value serialized in the `online` wire field.
   */
  online: boolean;
  /**
   * Required object value serialized in the `preAuthKey` wire field.
   */
  preAuthKey: NodePreAuthKey;
  /**
   * Required enumerated value serialized in the `registerMethod` wire field.
   */
  registerMethod:
    | "REGISTER_METHOD_UNSPECIFIED"
    | "REGISTER_METHOD_AUTH_KEY"
    | "REGISTER_METHOD_CLI"
    | "REGISTER_METHOD_OIDC"
    | (string & {});
  /**
   * Required array value serialized in the `subnetRoutes` wire field.
   */
  subnetRoutes: string[];
  /**
   * Required array value serialized in the `tags` wire field.
   */
  tags: string[];
  /**
   * Required object value serialized in the `user` wire field.
   */
  user: User;
}

/**
 * Typed representation of the `NodePreAuthKey` API schema.
 */
export interface NodePreAuthKey {
  /**
   * Required array value serialized in the `aclTags` wire field.
   */
  aclTags: string[];
  /**
   * Required `date-time`-formatted value serialized in the `createdAt` wire field.
   */
  createdAt: string | null;
  /**
   * Required `boolean` value serialized in the `ephemeral` wire field.
   */
  ephemeral: boolean;
  /**
   * Required `date-time`-formatted value serialized in the `expiration` wire field.
   */
  expiration: string | null;
  /**
   * Required `uint64`-formatted value serialized in the `id` wire field.
   */
  id: string;
  /**
   * Required `string` value serialized in the `key` wire field.
   */
  key: string;
  /**
   * Required `boolean` value serialized in the `reusable` wire field.
   */
  reusable: boolean;
  /**
   * Required `boolean` value serialized in the `used` wire field.
   */
  used: boolean;
  /**
   * Required object value serialized in the `user` wire field.
   */
  user: User;
}

/**
 * Typed representation of the `User` API schema.
 */
export interface User {
  /**
   * Required `date-time`-formatted value serialized in the `createdAt` wire field.
   */
  createdAt: string;
  /**
   * Required `string` value serialized in the `displayName` wire field.
   */
  displayName: string;
  /**
   * Required `string` value serialized in the `email` wire field.
   */
  email: string;
  /**
   * Required `uint64`-formatted value serialized in the `id` wire field.
   */
  id: string;
  /**
   * Required `string` value serialized in the `name` wire field.
   */
  name: string;
  /**
   * Required `string` value serialized in the `profilePicUrl` wire field.
   */
  profilePicUrl: string;
  /**
   * Required `string` value serialized in the `provider` wire field.
   */
  provider: string;
  /**
   * Required `string` value serialized in the `providerId` wire field.
   */
  providerId: string;
}
