// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { User } from "./shared";

/**
 * Typed representation of the `CreateUserRequestBody` API schema.
 */
export interface CreateUserRequestBody {
  /**
   * Optional `string` value serialized in the `displayName` wire field.
   */
  displayName?: string;
  /**
   * Optional `string` value serialized in the `email` wire field.
   */
  email?: string;
  /**
   * Optional `string` value serialized in the `name` wire field.
   */
  name?: string;
  /**
   * Optional `string` value serialized in the `pictureUrl` wire field.
   */
  pictureUrl?: string;
}

/**
 * Typed representation of the `DeleteUserOutputBody` API schema.
 */
export type DeleteUserOutputBody = Record<string, never>;

/**
 * Typed representation of the `ListUsersOutputBody` API schema.
 */
export interface ListUsersOutputBody {
  /**
   * Required array value serialized in the `users` wire field.
   */
  users: User[];
}

/**
 * Typed representation of the `UserOutputBody` API schema.
 */
export interface UserOutputBody {
  /**
   * Required object value serialized in the `user` wire field.
   */
  user: User;
}
