// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import assert from "node:assert/strict";
import test from "node:test";

import {
  argumentsFor,
  echoedKeys,
  expectedResponses,
  matchesBytes,
  matchesExpected,
  matchesPagedExpected,
  routeFor,
  startMockServer,
} from "../helpers/mock-sdk.mjs";
import { configureClient } from "../../dist/client.js";
import { SdkHttpError } from "../../dist/errors.js";
import {
  debugCreateNode,
  listNodes,
  backfillNodeIps,
  registerNode,
  deleteNode,
  getNode,
  setApprovedRoutes,
  expireNode,
  renameNode,
  setTags,
} from "../../dist/methods/nodes.js";

// Assigned once the mock server has a port. Declared at module scope because
// the call map below is built here too, and a config-first SDK's call
// expressions reference `config` as their first argument — a `const` inside
// the test body would leave those references unresolved at call time.
let config;

// operationId → how to call that method with a resolved argument bag. This is
// the generated part: it encodes each method's real signature (argument order
// for positional style, the params object otherwise).
const CALL = {
  debugCreateNode: {
    route: "debugCreateNode",
    mediaType: "application/json",
    invoke: (bag) =>
      debugCreateNode(config, {
        key: bag.__body?.["key"],
        name: bag.__body?.["name"],
        routes: bag.__body?.["routes"],
        user: bag.__body?.["user"],
      }),
  },
  listNodes: {
    route: "listNodes",
    mediaType: null,
    invoke: (bag) => listNodes(config, { user: bag["user"] }),
  },
  backfillNodeIps: {
    route: "backfillNodeIPs",
    mediaType: null,
    invoke: (bag) => backfillNodeIps(config, { confirmed: bag["confirmed"] }),
  },
  registerNode: {
    route: "registerNode",
    mediaType: null,
    invoke: (bag) => registerNode(config, { user: bag["user"], key: bag["key"] }),
  },
  deleteNode: {
    route: "deleteNode",
    mediaType: null,
    invoke: (bag) => deleteNode(config, { nodeId: bag["nodeId"] }),
  },
  getNode: {
    route: "getNode",
    mediaType: null,
    invoke: (bag) => getNode(config, { nodeId: bag["nodeId"] }),
  },
  setApprovedRoutes: {
    route: "setApprovedRoutes",
    mediaType: "application/json",
    invoke: (bag) =>
      setApprovedRoutes(config, { routes: bag.__body?.["routes"], nodeId: bag["nodeId"] }),
  },
  expireNode: {
    route: "expireNode",
    mediaType: "application/json",
    invoke: (bag) =>
      expireNode(config, {
        disableExpiry: bag.__body?.["disableExpiry"],
        expiry: bag.__body?.["expiry"],
        nodeId: bag["nodeId"],
      }),
  },
  renameNode: {
    route: "renameNode",
    mediaType: null,
    invoke: (bag) => renameNode(config, { nodeId: bag["nodeId"], newName: bag["newName"] }),
  },
  setTags: {
    route: "setTags",
    mediaType: "application/json",
    invoke: (bag) => setTags(config, { tags: bag.__body?.["tags"], nodeId: bag["nodeId"] }),
  },
};

test("nodes methods reach the mock server and decode its responses", async (t) => {
  const mock = await startMockServer();
  config = configureClient({ baseUrl: mock.baseUrl });
  void config;
  try {
    for (const [methodName, entry] of Object.entries(CALL)) {
      await t.test(methodName, async () => {
        const route = routeFor(entry.route);
        assert.ok(route, `no mock route for ${entry.route}`);

        let invocationError = null;
        let response;
        let streamed = false;
        try {
          const invoked = entry.invoke(argumentsFor(route, entry.mediaType));
          if (invoked?.[Symbol.asyncIterator]) {
            streamed = true;
            const events = [];
            // An auto-paginating method is an async generator over a static
            // mock: an example carrying has_more: true would never terminate.
            for await (const event of invoked) {
              events.push(event);
              if (events.length >= 50) break;
            }
            response = events.length === 1 ? events[0] : events;
          } else {
            response = await invoked;
          }
        } catch (error) {
          invocationError = error;
        }

        const expected = expectedResponses(route);
        if ((route.responseModes ?? []).length === 0) {
          assert.ok(
            invocationError instanceof SdkHttpError,
            `${methodName} should surface the declared non-2xx response as an HTTP error`,
          );
          return;
        }
        if (invocationError) throw invocationError;
        if (expected.length > 0) {
          assert.ok(
            expected.some(
              (mode) =>
                matchesBytes(response, mode) ||
                matchesExpected(response, mode.example, echoedKeys(route)) ||
                (streamed && matchesPagedExpected(response, mode.example, echoedKeys(route))),
            ),
            `${methodName} decoded a response matching none of its declared 2xx examples`,
          );
        }
      });
    }
  } finally {
    mock.stop();
  }
});
