// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type { ClientConfig, LoggingConfig } from "./client";
import { ApiKeysNamespace } from "./methods/apiKeys";
import { AuthNamespace } from "./methods/auth";
import { NodesNamespace } from "./methods/nodes";
import { HealthNamespace } from "./methods/health";
import { PolicyNamespace } from "./methods/policy";
import { PreAuthKeysNamespace } from "./methods/preAuthKeys";
import { UsersNamespace } from "./methods/users";

export class Headscale {
  private readonly _config: ClientConfig;
  readonly apiKeys: ApiKeysNamespace;
  readonly auth: AuthNamespace;
  readonly nodes: NodesNamespace;
  readonly health: HealthNamespace;
  readonly policy: PolicyNamespace;
  readonly preAuthKeys: PreAuthKeysNamespace;
  readonly users: UsersNamespace;

  constructor(config: ClientConfig) {
    this._config = config;
    this.apiKeys = new ApiKeysNamespace(config);
    this.auth = new AuthNamespace(config);
    this.nodes = new NodesNamespace(config);
    this.health = new HealthNamespace(config);
    this.policy = new PolicyNamespace(config);
    this.preAuthKeys = new PreAuthKeysNamespace(config);
    this.users = new UsersNamespace(config);
  }

  /**
   * Turns SDK logging on and configures it. Logging is OFF by default — this
   * SDK reports nothing until you call this (or construct the client with
   * `logging: { enabled: true }`). Reports go to the endpoint this build was
   * generated with, or to the `endpoint` you pass; with neither, nothing is sent.
   * Pass `{ enabled: false }` to turn it off.
   */
  setLoggingConfig(config: LoggingConfig): void {
    this._config.logging = { ...this._config.logging, enabled: true, ...config };
  }
}
