// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import { SdkValidationError } from "./errors";

import { validateDateTime, validateUri } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  ApiKey: {
    type: "object",
    required: ["id", "prefix", "expiration", "createdAt", "lastSeen"],
    properties: {
      createdAt: { type: "string", nullable: true, format: "date-time" },
      expiration: { type: "string", nullable: true, format: "date-time" },
      lastSeen: { type: "string", nullable: true, format: "date-time" },
    },
  },
  AuthRegisterOutputBody: {
    type: "object",
    required: ["node"],
    properties: { node: { ref: "Node" } },
  },
  BackfillNodeIPsOutputBody: { type: "object", required: ["changes"] },
  CreateApiKeyOutputBody: { type: "object", required: ["apiKey"] },
  CreateApiKeyRequestBody: {
    type: "object",
    properties: { expiration: { type: "string", format: "date-time" } },
  },
  CreatePreAuthKeyRequestBody: {
    type: "object",
    properties: { expiration: { type: "string", format: "date-time" } },
  },
  ErrorModel: {
    type: "object",
    properties: {
      instance: { type: "string", format: "uri" },
      type: { type: "string", format: "uri" },
    },
  },
  ExpireNodeRequestBody: {
    type: "object",
    properties: { expiry: { type: "string", format: "date-time" } },
  },
  HealthResponseBody: { type: "object", required: ["databaseConnectivity"] },
  ListApiKeysOutputBody: {
    type: "object",
    required: ["apiKeys"],
    properties: { apiKeys: { type: "array", items: { ref: "ApiKey" } } },
  },
  ListNodesOutputBody: {
    type: "object",
    required: ["nodes"],
    properties: { nodes: { type: "array", items: { ref: "Node" } } },
  },
  ListPreAuthKeysOutputBody: {
    type: "object",
    required: ["preAuthKeys"],
    properties: { preAuthKeys: { type: "array", items: { ref: "PreAuthKey" } } },
  },
  ListUsersOutputBody: {
    type: "object",
    required: ["users"],
    properties: { users: { type: "array", items: { ref: "User" } } },
  },
  Node: {
    type: "object",
    required: [
      "id",
      "machineKey",
      "nodeKey",
      "discoKey",
      "ipAddresses",
      "name",
      "user",
      "lastSeen",
      "expiry",
      "preAuthKey",
      "createdAt",
      "registerMethod",
      "givenName",
      "online",
      "approvedRoutes",
      "availableRoutes",
      "subnetRoutes",
      "tags",
    ],
    properties: {
      createdAt: { type: "string", format: "date-time" },
      expiry: { type: "string", nullable: true, format: "date-time" },
      lastSeen: { type: "string", nullable: true, format: "date-time" },
      preAuthKey: { ref: "NodePreAuthKey" },
      user: { ref: "User" },
    },
  },
  NodeOutputBody: { type: "object", required: ["node"], properties: { node: { ref: "Node" } } },
  NodePreAuthKey: {
    type: "object",
    required: [
      "user",
      "id",
      "key",
      "reusable",
      "ephemeral",
      "used",
      "expiration",
      "createdAt",
      "aclTags",
    ],
    properties: {
      createdAt: { type: "string", nullable: true, format: "date-time" },
      expiration: { type: "string", nullable: true, format: "date-time" },
      user: { ref: "User" },
    },
  },
  PolicyResponseBody: {
    type: "object",
    required: ["policy", "updatedAt"],
    properties: { updatedAt: { type: "string", format: "date-time" } },
  },
  PreAuthKey: {
    type: "object",
    required: [
      "user",
      "id",
      "key",
      "reusable",
      "ephemeral",
      "used",
      "expiration",
      "createdAt",
      "aclTags",
    ],
    properties: {
      createdAt: { type: "string", format: "date-time" },
      expiration: { type: "string", format: "date-time" },
      user: { ref: "User" },
    },
  },
  PreAuthKeyOutputBody: {
    type: "object",
    required: ["preAuthKey"],
    properties: { preAuthKey: { ref: "PreAuthKey" } },
  },
  User: {
    type: "object",
    required: [
      "id",
      "name",
      "createdAt",
      "displayName",
      "email",
      "providerId",
      "provider",
      "profilePicUrl",
    ],
    properties: { createdAt: { type: "string", format: "date-time" } },
  },
  UserOutputBody: { type: "object", required: ["user"], properties: { user: { ref: "User" } } },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const validationFailure = (field: string, message: string): never => {
  throw new SdkValidationError(field, "required", message);
};

const requiredValue = (field: string): never =>
  validationFailure(field, `Validation failed for '${field}': value is required`);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return validationFailure(field, `Validation failed for '${field}': value is not nullable`);
  }

  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      if (!Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined) {
        requiredValue(childField(field, property));
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "uri") validateUri(field, value as string);

  if (schema.format === "date-time") validateDateTime(field, value as string);

  return value;
};

/** Validates a decoded component model and returns the original value. */
export function decodeModel<T>(value: unknown, typeName: string): T {
  const schema = modelSchemas[typeName];
  if (!schema) return value as T;
  return validateNode(value, schema, "") as T;
}
