// Code generated by Octri SDK Studio. DO NOT EDIT.
// This file is machine-generated from your OpenAPI spec.

import type * as Types from "./types";
import { fromWire, toWire } from "./client";
import { SdkValidationError } from "./errors";

import { validateDateTime, validateUri } from "./validation";

type RuntimeRecord = Record<string, unknown>;

interface RuntimeSchema {
  ref?: string;
  type?: string | readonly string[];
  nullable?: boolean;
  enum?: readonly unknown[];
  required?: readonly string[];
  properties?: Readonly<Record<string, RuntimeSchema>>;
  items?: RuntimeSchema;
  additionalProperties?: RuntimeSchema;
  oneOf?: readonly RuntimeSchema[];
  anyOf?: readonly RuntimeSchema[];
  allOf?: readonly RuntimeSchema[];
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number | boolean;
  exclusiveMaximum?: number | boolean;
  multipleOf?: number;
  minLength?: number;
  maxLength?: number;
  minItems?: number;
  maxItems?: number;
  pattern?: string;
  format?: "email" | "uri" | "uuid" | "date" | "date-time";
}

const modelSchemas: Readonly<Record<string, RuntimeSchema>> = {
  ApiKey: {
    type: "object",
    required: ["id", "prefix", "expiration", "createdAt", "lastSeen"],
    properties: {
      createdAt: { type: "string", nullable: true, format: "date-time" },
      expiration: { type: "string", nullable: true, format: "date-time" },
      id: { type: "string" },
      lastSeen: { type: "string", nullable: true, format: "date-time" },
      prefix: { type: "string" },
    },
  },
  AuthRegisterOutputBody: {
    type: "object",
    required: ["node"],
    properties: { node: { ref: "Node" } },
  },
  BackfillNodeIPsOutputBody: {
    type: "object",
    required: ["changes"],
    properties: { changes: { type: "array", items: { type: "string" } } },
  },
  CreateApiKeyOutputBody: {
    type: "object",
    required: ["apiKey"],
    properties: { apiKey: { type: "string" } },
  },
  CreateApiKeyRequestBody: {
    type: "object",
    properties: { expiration: { type: "string", format: "date-time" } },
  },
  CreatePreAuthKeyRequestBody: {
    type: "object",
    properties: {
      aclTags: { type: "array", nullable: true, items: { type: "string" } },
      ephemeral: { type: "boolean" },
      expiration: { type: "string", format: "date-time" },
      reusable: { type: "boolean" },
      user: { type: "string" },
    },
  },
  ErrorModel: {
    type: "object",
    properties: {
      detail: { type: "string" },
      errors: { type: "array", nullable: true, items: { ref: "ErrorDetail" } },
      instance: { type: "string", format: "uri" },
      status: { type: "integer" },
      title: { type: "string" },
      type: { type: "string", format: "uri" },
    },
  },
  ExpireNodeRequestBody: {
    type: "object",
    properties: {
      disableExpiry: { type: "boolean" },
      expiry: { type: "string", format: "date-time" },
    },
  },
  HealthResponseBody: {
    type: "object",
    required: ["databaseConnectivity"],
    properties: { databaseConnectivity: { type: "boolean" } },
  },
  ListApiKeysOutputBody: {
    type: "object",
    required: ["apiKeys"],
    properties: { apiKeys: { type: "array", items: { ref: "ApiKey" } } },
  },
  ListNodesOutputBody: {
    type: "object",
    required: ["nodes"],
    properties: { nodes: { type: "array", items: { ref: "Node" } } },
  },
  ListPreAuthKeysOutputBody: {
    type: "object",
    required: ["preAuthKeys"],
    properties: { preAuthKeys: { type: "array", items: { ref: "PreAuthKey" } } },
  },
  ListUsersOutputBody: {
    type: "object",
    required: ["users"],
    properties: { users: { type: "array", items: { ref: "User" } } },
  },
  Node: {
    type: "object",
    required: [
      "id",
      "machineKey",
      "nodeKey",
      "discoKey",
      "ipAddresses",
      "name",
      "user",
      "lastSeen",
      "expiry",
      "preAuthKey",
      "createdAt",
      "registerMethod",
      "givenName",
      "online",
      "approvedRoutes",
      "availableRoutes",
      "subnetRoutes",
      "tags",
    ],
    properties: {
      approvedRoutes: { type: "array", items: { type: "string" } },
      availableRoutes: { type: "array", items: { type: "string" } },
      createdAt: { type: "string", format: "date-time" },
      discoKey: { type: "string" },
      expiry: { type: "string", nullable: true, format: "date-time" },
      givenName: { type: "string" },
      id: { type: "string" },
      ipAddresses: { type: "array", items: { type: "string" } },
      lastSeen: { type: "string", nullable: true, format: "date-time" },
      machineKey: { type: "string" },
      name: { type: "string" },
      nodeKey: { type: "string" },
      online: { type: "boolean" },
      preAuthKey: { ref: "NodePreAuthKey" },
      registerMethod: { type: "string" },
      subnetRoutes: { type: "array", items: { type: "string" } },
      tags: { type: "array", items: { type: "string" } },
      user: { ref: "User" },
    },
  },
  NodeOutputBody: { type: "object", required: ["node"], properties: { node: { ref: "Node" } } },
  NodePreAuthKey: {
    type: "object",
    required: [
      "user",
      "id",
      "key",
      "reusable",
      "ephemeral",
      "used",
      "expiration",
      "createdAt",
      "aclTags",
    ],
    properties: {
      aclTags: { type: "array", items: { type: "string" } },
      createdAt: { type: "string", nullable: true, format: "date-time" },
      ephemeral: { type: "boolean" },
      expiration: { type: "string", nullable: true, format: "date-time" },
      id: { type: "string" },
      key: { type: "string" },
      reusable: { type: "boolean" },
      used: { type: "boolean" },
      user: { ref: "User" },
    },
  },
  PolicyResponseBody: {
    type: "object",
    required: ["policy", "updatedAt"],
    properties: { policy: { type: "string" }, updatedAt: { type: "string", format: "date-time" } },
  },
  PreAuthKey: {
    type: "object",
    required: [
      "user",
      "id",
      "key",
      "reusable",
      "ephemeral",
      "used",
      "expiration",
      "createdAt",
      "aclTags",
    ],
    properties: {
      aclTags: { type: "array", items: { type: "string" } },
      createdAt: { type: "string", format: "date-time" },
      ephemeral: { type: "boolean" },
      expiration: { type: "string", format: "date-time" },
      id: { type: "string" },
      key: { type: "string" },
      reusable: { type: "boolean" },
      used: { type: "boolean" },
      user: { ref: "User" },
    },
  },
  PreAuthKeyOutputBody: {
    type: "object",
    required: ["preAuthKey"],
    properties: { preAuthKey: { ref: "PreAuthKey" } },
  },
  User: {
    type: "object",
    required: [
      "id",
      "name",
      "createdAt",
      "displayName",
      "email",
      "providerId",
      "provider",
      "profilePicUrl",
    ],
    properties: {
      createdAt: { type: "string", format: "date-time" },
      displayName: { type: "string" },
      email: { type: "string" },
      id: { type: "string" },
      name: { type: "string" },
      profilePicUrl: { type: "string" },
      provider: { type: "string" },
      providerId: { type: "string" },
    },
  },
  UserOutputBody: { type: "object", required: ["user"], properties: { user: { ref: "User" } } },
};

const isRecord = (value: unknown): value is RuntimeRecord =>
  value !== null && typeof value === "object" && !Array.isArray(value);

const childField = (field: string, property: string): string =>
  field ? `${field}.${property}` : property;

const hasType = (schema: RuntimeSchema, type: string): boolean =>
  schema.type === type || (Array.isArray(schema.type) && schema.type.includes(type));

const allowsNull = (schema: RuntimeSchema | undefined, seen = new Set<string>()): boolean => {
  if (!schema) return false;
  if (schema.nullable === true || hasType(schema, "null")) return true;
  if (!schema.ref || seen.has(schema.ref)) return false;
  seen.add(schema.ref);
  const referenced = modelSchemas[schema.ref];
  return referenced ? allowsNull(referenced, seen) : false;
};

const validationFailure = (field: string, code: "required", message: string): never => {
  throw new SdkValidationError(field, code, message);
};

const validateNode = (value: unknown, schema: RuntimeSchema, field: string): unknown => {
  if (schema.ref) {
    const referenced = modelSchemas[schema.ref];
    return referenced ? validateNode(value, referenced, field) : value;
  }

  if (value === null) {
    if (schema.nullable === true || hasType(schema, "null")) return value;
    return value;
  }

  if (schema.allOf) {
    for (const member of schema.allOf) validateNode(value, member, field);
  }

  if (schema.oneOf || schema.anyOf) {
    const members = schema.oneOf ?? schema.anyOf ?? [];
    let firstError: unknown;
    for (const member of members) {
      try {
        return validateNode(value, member, field);
      } catch (error) {
        firstError ??= error;
      }
    }
    if (firstError instanceof Error) throw firstError;
  }

  if (hasType(schema, "object") || schema.properties) {
    if (!isRecord(value)) return value;
    for (const property of schema.required ?? []) {
      const propertyValue = value[property];
      const propertySchema = schema.properties?.[property];
      const missing =
        !Object.prototype.hasOwnProperty.call(value, property) || propertyValue === undefined;
      const invalidNull = propertyValue === null && !allowsNull(propertySchema);
      if (missing || invalidNull) {
        validationFailure(
          childField(field, property),
          "required",
          `Validation failed for '${childField(field, property)}': value is required`,
        );
      }
    }
    for (const [property, propertySchema] of Object.entries(schema.properties ?? {})) {
      if (Object.prototype.hasOwnProperty.call(value, property)) {
        validateNode(value[property], propertySchema, childField(field, property));
      }
    }
    if (schema.additionalProperties) {
      for (const [property, propertyValue] of Object.entries(value)) {
        if (!(property in (schema.properties ?? {}))) {
          validateNode(propertyValue, schema.additionalProperties, childField(field, property));
        }
      }
    }
  }

  if (hasType(schema, "array")) {
    if (!Array.isArray(value)) return value;
    if (schema.items) {
      value.forEach((item, index) =>
        validateNode(item, schema.items as RuntimeSchema, childField(field, String(index))),
      );
    }
  }

  if (schema.format === "uri") validateUri(field, value as string);

  if (schema.format === "date-time") validateDateTime(field, value as string);

  return value;
};

const validateModel = <T>(value: T, typeName: string): T => {
  const schema = modelSchemas[typeName];
  return schema ? (validateNode(value, schema, "") as T) : value;
};

export const modelConstructionStyle = "typed-record" as const;

/** Constructs a validated ApiKey model value. */
export function createApiKeyModel(value: Types.ApiKey): Types.ApiKey {
  return validateModel({ ...value }, "ApiKey");
}

/** Constructs a validated AuthApproveOutputBody model value. */
export function createAuthApproveOutputBody(
  value: Types.AuthApproveOutputBody,
): Types.AuthApproveOutputBody {
  return validateModel({ ...value }, "AuthApproveOutputBody");
}

/** Constructs a validated AuthApproveRequestBody model value. */
export function createAuthApproveRequestBody(
  value: Types.AuthApproveRequestBody,
): Types.AuthApproveRequestBody {
  return validateModel({ ...value }, "AuthApproveRequestBody");
}

/** Constructs a validated AuthRegisterOutputBody model value. */
export function createAuthRegisterOutputBody(
  value: Types.AuthRegisterOutputBody,
): Types.AuthRegisterOutputBody {
  return validateModel({ ...value }, "AuthRegisterOutputBody");
}

/** Constructs a validated AuthRegisterRequestBody model value. */
export function createAuthRegisterRequestBody(
  value: Types.AuthRegisterRequestBody,
): Types.AuthRegisterRequestBody {
  return validateModel({ ...value }, "AuthRegisterRequestBody");
}

/** Constructs a validated AuthRejectOutputBody model value. */
export function createAuthRejectOutputBody(
  value: Types.AuthRejectOutputBody,
): Types.AuthRejectOutputBody {
  return validateModel({ ...value }, "AuthRejectOutputBody");
}

/** Constructs a validated AuthRejectRequestBody model value. */
export function createAuthRejectRequestBody(
  value: Types.AuthRejectRequestBody,
): Types.AuthRejectRequestBody {
  return validateModel({ ...value }, "AuthRejectRequestBody");
}

/** Constructs a validated BackfillNodeIPsOutputBody model value. */
export function createBackfillNodeIPsOutputBody(
  value: Types.BackfillNodeIPsOutputBody,
): Types.BackfillNodeIPsOutputBody {
  return validateModel({ ...value }, "BackfillNodeIPsOutputBody");
}

/** Constructs a validated CheckPolicyOutputBody model value. */
export function createCheckPolicyOutputBody(
  value: Types.CheckPolicyOutputBody,
): Types.CheckPolicyOutputBody {
  return validateModel({ ...value }, "CheckPolicyOutputBody");
}

/** Constructs a validated CreateApiKeyOutputBody model value. */
export function createCreateApiKeyOutputBody(
  value: Types.CreateApiKeyOutputBody,
): Types.CreateApiKeyOutputBody {
  return validateModel({ ...value }, "CreateApiKeyOutputBody");
}

/** Constructs a validated CreateApiKeyRequestBody model value. */
export function createCreateApiKeyRequestBody(
  value: Types.CreateApiKeyRequestBody,
): Types.CreateApiKeyRequestBody {
  return validateModel({ ...value }, "CreateApiKeyRequestBody");
}

/** Constructs a validated CreatePreAuthKeyRequestBody model value. */
export function createCreatePreAuthKeyRequestBody(
  value: Types.CreatePreAuthKeyRequestBody,
): Types.CreatePreAuthKeyRequestBody {
  return validateModel({ ...value }, "CreatePreAuthKeyRequestBody");
}

/** Constructs a validated CreateUserRequestBody model value. */
export function createCreateUserRequestBody(
  value: Types.CreateUserRequestBody,
): Types.CreateUserRequestBody {
  return validateModel({ ...value }, "CreateUserRequestBody");
}

/** Constructs a validated DebugCreateNodeRequestBody model value. */
export function createDebugCreateNodeRequestBody(
  value: Types.DebugCreateNodeRequestBody,
): Types.DebugCreateNodeRequestBody {
  return validateModel({ ...value }, "DebugCreateNodeRequestBody");
}

/** Constructs a validated DeleteApiKeyOutputBody model value. */
export function createDeleteApiKeyOutputBody(
  value: Types.DeleteApiKeyOutputBody,
): Types.DeleteApiKeyOutputBody {
  return validateModel({ ...value }, "DeleteApiKeyOutputBody");
}

/** Constructs a validated DeleteNodeOutputBody model value. */
export function createDeleteNodeOutputBody(
  value: Types.DeleteNodeOutputBody,
): Types.DeleteNodeOutputBody {
  return validateModel({ ...value }, "DeleteNodeOutputBody");
}

/** Constructs a validated DeletePreAuthKeyOutputBody model value. */
export function createDeletePreAuthKeyOutputBody(
  value: Types.DeletePreAuthKeyOutputBody,
): Types.DeletePreAuthKeyOutputBody {
  return validateModel({ ...value }, "DeletePreAuthKeyOutputBody");
}

/** Constructs a validated DeleteUserOutputBody model value. */
export function createDeleteUserOutputBody(
  value: Types.DeleteUserOutputBody,
): Types.DeleteUserOutputBody {
  return validateModel({ ...value }, "DeleteUserOutputBody");
}

/** Constructs a validated ErrorDetail model value. */
export function createErrorDetail(value: Types.ErrorDetail): Types.ErrorDetail {
  return validateModel({ ...value }, "ErrorDetail");
}

/** Constructs a validated ErrorModel model value. */
export function createErrorModel(value: Types.ErrorModel): Types.ErrorModel {
  return validateModel({ ...value }, "ErrorModel");
}

/** Constructs a validated ExpireApiKeyOutputBody model value. */
export function createExpireApiKeyOutputBody(
  value: Types.ExpireApiKeyOutputBody,
): Types.ExpireApiKeyOutputBody {
  return validateModel({ ...value }, "ExpireApiKeyOutputBody");
}

/** Constructs a validated ExpireApiKeyRequestBody model value. */
export function createExpireApiKeyRequestBody(
  value: Types.ExpireApiKeyRequestBody,
): Types.ExpireApiKeyRequestBody {
  return validateModel({ ...value }, "ExpireApiKeyRequestBody");
}

/** Constructs a validated ExpireNodeRequestBody model value. */
export function createExpireNodeRequestBody(
  value: Types.ExpireNodeRequestBody,
): Types.ExpireNodeRequestBody {
  return validateModel({ ...value }, "ExpireNodeRequestBody");
}

/** Constructs a validated ExpirePreAuthKeyOutputBody model value. */
export function createExpirePreAuthKeyOutputBody(
  value: Types.ExpirePreAuthKeyOutputBody,
): Types.ExpirePreAuthKeyOutputBody {
  return validateModel({ ...value }, "ExpirePreAuthKeyOutputBody");
}

/** Constructs a validated ExpirePreAuthKeyRequestBody model value. */
export function createExpirePreAuthKeyRequestBody(
  value: Types.ExpirePreAuthKeyRequestBody,
): Types.ExpirePreAuthKeyRequestBody {
  return validateModel({ ...value }, "ExpirePreAuthKeyRequestBody");
}

/** Constructs a validated HealthResponseBody model value. */
export function createHealthResponseBody(
  value: Types.HealthResponseBody,
): Types.HealthResponseBody {
  return validateModel({ ...value }, "HealthResponseBody");
}

/** Constructs a validated ListApiKeysOutputBody model value. */
export function createListApiKeysOutputBody(
  value: Types.ListApiKeysOutputBody,
): Types.ListApiKeysOutputBody {
  return validateModel({ ...value }, "ListApiKeysOutputBody");
}

/** Constructs a validated ListNodesOutputBody model value. */
export function createListNodesOutputBody(
  value: Types.ListNodesOutputBody,
): Types.ListNodesOutputBody {
  return validateModel({ ...value }, "ListNodesOutputBody");
}

/** Constructs a validated ListPreAuthKeysOutputBody model value. */
export function createListPreAuthKeysOutputBody(
  value: Types.ListPreAuthKeysOutputBody,
): Types.ListPreAuthKeysOutputBody {
  return validateModel({ ...value }, "ListPreAuthKeysOutputBody");
}

/** Constructs a validated ListUsersOutputBody model value. */
export function createListUsersOutputBody(
  value: Types.ListUsersOutputBody,
): Types.ListUsersOutputBody {
  return validateModel({ ...value }, "ListUsersOutputBody");
}

/** Constructs a validated Node model value. */
export function createNode(value: Types.Node): Types.Node {
  return validateModel({ ...value }, "Node");
}

/** Constructs a validated NodeOutputBody model value. */
export function createNodeOutputBody(value: Types.NodeOutputBody): Types.NodeOutputBody {
  return validateModel({ ...value }, "NodeOutputBody");
}

/** Constructs a validated NodePreAuthKey model value. */
export function createNodePreAuthKey(value: Types.NodePreAuthKey): Types.NodePreAuthKey {
  return validateModel({ ...value }, "NodePreAuthKey");
}

/** Constructs a validated PolicyRequestBody model value. */
export function createPolicyRequestBody(value: Types.PolicyRequestBody): Types.PolicyRequestBody {
  return validateModel({ ...value }, "PolicyRequestBody");
}

/** Constructs a validated PolicyResponseBody model value. */
export function createPolicyResponseBody(
  value: Types.PolicyResponseBody,
): Types.PolicyResponseBody {
  return validateModel({ ...value }, "PolicyResponseBody");
}

/** Constructs a validated PreAuthKey model value. */
export function createPreAuthKeyModel(value: Types.PreAuthKey): Types.PreAuthKey {
  return validateModel({ ...value }, "PreAuthKey");
}

/** Constructs a validated PreAuthKeyOutputBody model value. */
export function createPreAuthKeyOutputBody(
  value: Types.PreAuthKeyOutputBody,
): Types.PreAuthKeyOutputBody {
  return validateModel({ ...value }, "PreAuthKeyOutputBody");
}

/** Constructs a validated SetApprovedRoutesRequestBody model value. */
export function createSetApprovedRoutesRequestBody(
  value: Types.SetApprovedRoutesRequestBody,
): Types.SetApprovedRoutesRequestBody {
  return validateModel({ ...value }, "SetApprovedRoutesRequestBody");
}

/** Constructs a validated SetTagsRequestBody model value. */
export function createSetTagsRequestBody(
  value: Types.SetTagsRequestBody,
): Types.SetTagsRequestBody {
  return validateModel({ ...value }, "SetTagsRequestBody");
}

/** Constructs a validated User model value. */
export function createUserModel(value: Types.User): Types.User {
  return validateModel({ ...value }, "User");
}

/** Constructs a validated UserOutputBody model value. */
export function createUserOutputBody(value: Types.UserOutputBody): Types.UserOutputBody {
  return validateModel({ ...value }, "UserOutputBody");
}

/** Serializes a constructed model using the generated wire-name mapping. */
export function serializeModel<T>(value: T, typeName: string): unknown {
  return toWire(validateModel(value, typeName), typeName);
}

/** Decodes and validates a wire model through the generated public surface. */
export function deserializeModel<T>(value: unknown, typeName: string): T {
  return validateModel<T>(fromWire(value, typeName) as T, typeName);
}
